apiVersion: v2
name: snipeit
description: A Helm chart for providing snipe-it to kubernetes

home: https://github.com/jcxldn/syntax-helm-charts
icon: https://github.com/snipe/snipe-it/blob/eb9cfbaed6fc830e9b114c625896a636842f2d1a/public/img/demo/snipe-logo-bug.png?raw=true

type: application
version: 1.1.8
appVersion: "8.1.0"

keywords:
- snipeit
- inventory
- asset management

sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb
- https://github.com/snipe/snipe-it

dependencies:
  - name: mariadb
    version: "20.5.5"
    repository: "https://charts.bitnami.com/bitnami"
