apiVersion: v2
name: teamspeak
description: A Helm chart for providing teamspeak server to kubernetes

home: https://github.com/jcxldn/syntax-helm-charts
icon: https://upload.wikimedia.org/wikipedia/commons/e/ec/TeamSpeak_logo_renovado.png

type: application
version: 0.9.3
appVersion: "3.13.7"

keywords:
- teamspeak
- voip

sources:
- https://hub.docker.com/_/teamspeak/

dependencies:
  - name: mariadb
    version: "20.5.5"
    repository: "https://charts.bitnami.com/bitnami"