{{- if and .Values.superuserPassword.generate (not .Values.superuserPassword.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mumble.fullname" . }}-superuser-password
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ .Values.superuserPassword.existingSecretKey | default "password" }}: {{ randAlphaNum (int .Values.superuserPassword.length) | quote }}
{{- end }}