apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}