---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snipeit.fullname" . }}
  labels:
    {{- include "snipeit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "snipeit.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snipeit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: set-session-permission
          image: docker.io/alpine:latest
          command: ["sh", "-c", "chown -R 100:101 /var/www/html/storage/framework/sessions"]
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.snipeit.image.repository }}:{{ .Values.snipeit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.snipeit.image.pullPolicy }}
          env:
            - name: DB_USERNAME 
              value: "{{ .Values.mariadb.auth.username }}"
            - name: DB_PASSWORD 
              value: "{{ .Values.mariadb.auth.password }}"
            - name: DB_DATABASE 
              value: "{{ .Values.mariadb.auth.database }}"
            - name: DB_PORT 
              value: "{{ .Values.mariadb.auth.port }}"
            - name: DB_HOST 
              value: "{{ .Release.Name }}-mariadb"
            - name: APP_KEY 
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.snipeit.config.appKey.name }}"
                  key: APP_KEY
            - name: APP_ENV
              value: "{{ .Values.snipeit.config.env }}"
            - name: APP_DEBUG
              value: "{{ .Values.snipeit.config.debug }}"
            - name: APP_URL
              value: "{{ .Values.snipeit.config.url }}"
            - name: APP_TIMEZONE
              value: "{{ .Values.snipeit.config.timezone }}"
            - name: APP_LOCALE
              value: "{{ .Values.snipeit.config.locale }}"
            - name: MAIL_MAILER
              value: "{{ .Values.snipeit.config.mail.mailer }}"
            - name: MAIL_HOST
              value: "{{ .Values.snipeit.config.mail.host }}"
            - name: MAIL_PORT
              value: "{{ .Values.snipeit.config.mail.port }}"
            - name: MAIL_USERNAME
              value: "{{ .Values.snipeit.config.mail.username }}"
            - name: MAIL_PASSWORD
              value: "{{ .Values.snipeit.config.mail.password }}"
            - name: MAIL_FROM_ADDR
              value: "{{ .Values.snipeit.config.mail.from.addr }}"
            - name: MAIL_FROM_NAME
              value: "{{ .Values.snipeit.config.mail.from.name }}"
            - name: MAIL_REPLYTO_ADDR
              value: "{{ .Values.snipeit.config.mail.reply.addr }}"
            - name: MAIL_REPLYTO_NAME
              value: "{{ .Values.snipeit.config.mail.reply.name }}"
            - name: MAIL_AUTO_EMBED
              value: "{{ .Values.snipeit.config.mail.autoembed.enabled }}"
            - name: MAIL_AUTO_EMBED_METHOD
              value: "{{ .Values.snipeit.config.mail.autoembed.method }}"
            - name: MAIL_TLS_VERIFY_PEER
              value: "{{ .Values.snipeit.config.mail.tlsverifypeer }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
